'use strict';

const mongoose = require('mongoose');
const { Schema } = mongoose;

const { applyBasePlugins } = require('../../core/plugins');
const { ACTIVATION_CODE_STATUS, EDUCATION_LEVELS } = require('../../core/constants');

/**
 * Single-use registration credential issued by an instructor.
 *
 * Students cannot self-register; they must present a code that is unused and
 * unexpired. The code may be pre-bound to an email, education level and initial
 * collection so the resulting account arrives partially configured.
 */
const activationCodeSchema = new Schema(
  {
    code: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
      index: true,
    },
    status: {
      type: String,
      enum: Object.values(ACTIVATION_CODE_STATUS),
      default: ACTIVATION_CODE_STATUS.UNUSED,
      index: true,
    },
    /** Optional restriction: only this email may redeem the code. */
    intendedEmail: { type: String, trim: true, lowercase: true, default: null },
    intendedName: { type: String, trim: true, maxlength: 120, default: null },
    educationLevel: { type: String, enum: EDUCATION_LEVELS, default: null },
    /**
     * Collection the student is auto-enrolled into on successful registration.
     * Named `collectionId` because `collection` is a reserved Mongoose path.
     */
    collectionId: { type: Schema.Types.ObjectId, ref: 'Collection', default: null, index: true },

    expiresAt: { type: Date, required: true, index: true },
    /**
     * `null` marks a code auto-generated by the system at self-registration
     * (no instructor pre-issued it) — see `AuthService#registerStudent`.
     */
    issuedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null, index: true },

    usedAt: { type: Date, default: null },
    usedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },

    notes: { type: String, trim: true, maxlength: 1000 },
  },
  { timestamps: true }
);

applyBasePlugins(activationCodeSchema);

activationCodeSchema.index({ status: 1, expiresAt: 1 });
activationCodeSchema.index({ issuedBy: 1, createdAt: -1 });

/** True when the code can still be redeemed right now. */
activationCodeSchema.virtual('isRedeemable').get(function isRedeemable() {
  return (
    this.status === ACTIVATION_CODE_STATUS.UNUSED &&
    this.expiresAt instanceof Date &&
    this.expiresAt.getTime() > Date.now() &&
    !this.deletedAt
  );
});

activationCodeSchema.virtual('isExpired').get(function isExpired() {
  return this.expiresAt instanceof Date && this.expiresAt.getTime() <= Date.now();
});

module.exports = mongoose.model('ActivationCode', activationCodeSchema);
